a = input("Enter first number ")
b = input("Enter second number ")
x = int(a)
y = int(b)
sum = str(x + y)
diff = str(x - y)
prod = str(x * y)
divi = str(x / y)
modul = str(x % y)
expo = str(x ** y)

print(a + "+" + b + "= " + sum)
print(a + "-" + b + "= " + diff)
print(a + "*" + b + "= " + prod)
print(a + "/" + b + "= " + divi)
print(a + "%" + b + "= " + modul)
print(a + "^" + b + "= " + expo)

