a = input("Enter first number ")
b = input("Enter second number ")
x = int(a)
y = int (b)

print("Sum:")
print(x + y)
print("Difference:")
print(x - y)
print("Product:")
print(x * y)
print("Quetiont")
print(x / y)